### ISSUE TITLE
Project does not compile

### ISSUE THREAD

**Issue by danfusaro** [MatTaNg/joes-task#10]
I run `npm install && npm start` and get the following error:

@gr8fuljoe5  Are you seeing the same?

```
Failed to compile.

./src/index.js
  Line 9:  'BrowserRouter' is not defined  react/jsx-no-undef

Search for the keywords to learn more about each error.
```
https://github.com/MatTaNg/joes-task/blob/357784dc9116c6ce9696f92ee1070ff28f6f5954/package.json#L1

**Comment by gr8fuljoe5** [comment]
Fixed! That was on me... ;)
