### ISSUE TITLE
Random number generation

### ISSUE THREAD

**Issue by danfusaro** [MatTaNg/joes-task#11]
What is the significance of multiplying here?  If you think about it `Math.random()` is the same randomness as `Math.random() * 151` try something like ```Number.parseInt(Math.random() * Math.pow(15, 10))```

This should give you a random 15-digit number.

https://github.com/MatTaNg/joes-task/blob/357784dc9116c6ce9696f92ee1070ff28f6f5954/src/components/pokemonGenerator.js#L12

**Comment by gr8fuljoe5** [comment]
@MatTaNg What was the reason for closing this?

**Comment by MatTaNg** [comment]
The reason I am multiplying by 151 here is because there are 151 pokemon in the first generation so I need a number from 1 - 151.  So I think the logic is correct.  I didn't mean to close the ticket though - Not sure how that happened.

**Comment by danfusaro** [comment]
Ah, that makes sense, I stand corrected!
