### ISSUE TITLE
Favor deconstruction over paths

### ISSUE THREAD

**Issue by danfusaro** [MatTaNg/joes-task#13]
Path accessor:
```
render() { 
    return <span>{ this.state.pokemon.name.toUpperCase() }</span>
}
````
Deconstruction:
```
render() { 
    const { pokemon: { name: 'No name' } = {} } = this.state
    return <span>{ name.toUpperCase() }</span>
}
```
Why is this preferred?
If `this.state.pokemon` is null, this app will crash, furthermore, if `.name` is null the app will also crash because of the `.toUpperCase()` call.  Deconstruction is not only a way to avoid that but also allows you to define a default value inline.

**Comment by MatTaNg** [comment]
I'm not able to find this snippet of code.  Where should I utilize this technique?

```
render() { 
    return <span>{ this.state.pokemon.name.toUpperCase() }</span>
}
```

**Comment by danfusaro** [comment]
This is just a (non-existent) example.  It's more of a overall best
practices comment and not about any specific place in your code.

**Comment by MatTaNg** [comment]
Ah okay.  I'm going to close this ticket then.  You can reopen it if there's work to be done with this.
