### ISSUE TITLE
Give some thought to adhereing to a patterns styleguide

### ISSUE THREAD

**Issue by gr8fuljoe5** [MatTaNg/joes-task#14]
https://github.com/airbnb/javascript/tree/master/react

We use styleguides so any developer and seamlessly jump in and out of code bases and not leave an imprint in the code. Check out the AirBnb one for example. You can set it up through ESLint as well. 

But yeah, i would try to clean some of this code up so it's more readable and intuitive

**Comment by MatTaNg** [comment]
I'm going to close this since this is similar to the prettier story - And is also complete.
